language: python
dist: trusty
sudo: false
python:
  - 2.7
addons:
  apt:
    packages:
      - libspatialite-dev
install:
  - pip install -i https://pypi.pacificclimate.org/simple/ -r test_requirements.txt
  - pip install .
script: python setup.py test
