language: python
python:
  - 2.7
before_install:
  - sudo apt-get install -qq libspatialite-dev
install:
  - pip install -i https://pypi.pacificclimate.org/simple/ -r test_requirements.txt
  - pip install .
script: python setup.py test
